export const LIGHT = {
  COLORS: {
    BACKGROUND: '#FFFFFF',
    TOAST_BACKGROUND: '#FFFFFF',
    TEXT_INPUT_BACKGROUND: '#FFFFFF',
    TEXT_INPUT_NOT_EDITABLE_BACKGROUND: '#EEEEEE',
    BUTTON_BACKGROUND: '#0085FF',
    BUTTON_LOADING_BACKGROUND: '#707273',
    PANEL_BACKGROUND: '#F6F6F6',

    TEXT_PRIMARY: '#000000',
    TEXT_SECONDARY: '#666666',
    TEXT_PLACEHOLDER: '#798593',
    TEXT_BUTTON: '#FFFFFF'
  }
}
